import os

replacements = {
    '점수: 0': 'Score: 0',
    '최고: 0': 'Best: 0',
    '최종 점수: 0': 'Final Score: 0',
    '웨이브: 1': 'Wave: 1',
    '체력: 100': 'HP: 100',
    '탄약: ∞': 'Ammo: ∞',
    '점수:': 'Score:',
    '최고:': 'Best:',
    '최고 기록:': 'High Score:',
    '최종 점수:': 'Final Score:',
    '웨이브:': 'Wave:',
    '체력:': 'Health:',
    '탄약:': 'Ammo:',
    '공격:': 'Attack:',
    '이동:': 'Move:',
    '시점:': 'View:',
    '도달한 웨이브:': 'Wave Reached:',
    '최고 기록 갱신!': 'New High Score!',
    '최고 기록 갱신': 'New High Score',
    '최고 기록': 'High Score',
    '최고기록': 'High Score',
    '게임 시작! 적들을 처치하세요!': 'Game Start! Defeat the enemies!',
    '게임 시작! 적들을 처치하세요': 'Game Start! Defeat the enemies',
    '게임 시작': 'Start Game',
    '시작': 'Start',
    '게임 오버': 'Game Over',
    '게임오버': 'Game Over',
    '다시 시작': 'Restart',
    '계속하기': 'Continue',
    '남은 적': 'Enemies Left',
    '남은적': 'Enemies Left',
    '당신은 쓰러졌습니다.': 'You have fallen.',
    '당신은 쓰러졌습니다': 'You have fallen',
    '당신을 쓰러뜨린 적': 'Enemy that defeated you',
    '던전에서 무시무시한 적들을 처치하며 살아남으세요! 웨이브가 진행될수록 더 강력한 적들이 나타납니다.': 'Survive the dungeon by defeating terrifying enemies! Stronger enemies appear as waves progress.',
    '던전에서 무시무시한 적들을 처치하며 살아남으세요! 웨이브가 진행될수록 더 강력한 적들이 나타납니다': 'Survive the dungeon by defeating terrifying enemies! Stronger enemies appear as waves progress.',
    '클릭하여 조준 시작': 'Click to start aiming',
    '클릭하여 조준': 'Click to aim',
    '마우스를 클릭하여 게임을 시작하세요.': 'Click the mouse to start the game.',
    '마우스를 클릭하여 게임을 시작하세요': 'Click the mouse to start the game.',
    '포인터를 캔버스에 고정하려면 화면을 클릭하세요.': 'Click the screen to lock the pointer to the canvas.',
    '포인터를 캔버스에 고정하려면 화면을 클릭하세요': 'Click the screen to lock the pointer to the canvas.',
    '클릭하면 재개': 'Click to resume',
    '화면을 클릭해 조작 시작': 'Click screen to start',
    '화면을 클릭해 포인터를 다시 고정하면 전투를 이어갈 수 있습니다.': 'Click the screen to lock the pointer again and continue the battle.',
    '화면을 클릭해 포인터를 다시 고정하면 전투를 이어갈 수 있습니다': 'Click the screen to lock the pointer again and continue the battle.',
    '포인터 잠금을 사용하면 더 자연스럽게 조작됩니다.': 'Pointer lock allows more natural control.',
    '포인터 잠금을 사용하면 더 자연스럽게 조작됩니다': 'Pointer lock allows more natural control.',
    '데이터 로딩 중...': 'Loading data...',
    '도달 웨이브': 'Wave Reached',
    '처치 수': 'Kills',
    '최종 점수': 'Final Score',
    '탄약 상자 획득': 'Ammo Box Acquired',
    '탄약 획득': 'Ammo Acquired',
    '탄약이 부족합니다': 'Low Ammo',
    '탄약이 없습니다': 'Out of Ammo',
    '구급 상자 획득': 'Medkit Acquired',
    '보호막 획득': 'Shield Acquired',
    '체력 회복': 'Health Recovered',
    '체력 아이템: 파란색 구체': 'Health Item: Blue Sphere',
    '무기 교체': 'Switch Weapon',
    '권총 탄약': 'Pistol Ammo',
    '권총': 'Pistol',
    '라이플': 'Rifle',
    '산탄총은 근거리에서 매우 강력합니다.': 'Shotgun is very powerful at close range.',
    '산탄총 탄약': 'Shotgun Ammo',
    '산탄총': 'Shotgun',
    '샷건': 'Shotgun',
    '예비탄': 'Reserve Ammo',
    '장전 중...': 'Reloading...',
    '재장전 중...': 'Reloading...',
    '재장전': 'Reload',
    '재사용 대기': 'Cooldown',
    '발사': 'Fire',
    '조작법': 'Controls',
    '마우스 — 시점 회전': 'Mouse - Rotate View',
    '시점 회전': 'Rotate View',
    '좌클릭 — 공격': 'Left Click - Attack',
    '좌클릭': 'Left Click',
    '대시': 'Dash',
    '일시 정지': 'Pause',
    '일시정지': 'Pause',
    '메인으로': 'Main Menu',
    '새 웨이브 시작!': 'New Wave Started!',
    '웨이브 완료!': 'Wave Complete!',
    '웨이브 정리 완료': 'Wave Cleared',
    '웨이브 클리어 시 다음 웨이브 자동 시작': 'Next wave starts automatically when cleared',
    '웨이브 클리어!': 'Wave Cleared!',
    '웨이브를 클리어하고 살아남으세요!': 'Clear waves and survive!',
    '적 3종: 그런트(빠름) • 브루트(강함) • 헌터(균형)': '3 Enemies: Grunt(Fast) • Brute(Strong) • Hunter(Balanced)',
    '적 종류': 'Enemy Types',
    '적은 미로를 따라 추적합니다.': 'Enemies track you through the maze.',
    '정예 적': 'Elite Enemy',
    '중장갑 적': 'Heavy Armored Enemy',
    '추적 적': 'Tracking Enemy',
    '원거리 적': 'Ranged Enemy',
    '그런트': 'Grunt',
    '브루트': 'Brute',
    '레인저': 'Ranger',
    '스켈레톤: 보통 속도': 'Skeleton: Normal Speed',
    '악마: 빠르지만 약함': 'Demon: Fast but Weak',
    '좀비: 느리지만 강함': 'Zombie: Slow but Strong',
    '중장체': 'Heavy Body',
    '정찰체': 'Scout',
    '스펙터': 'Specter',
    '포자 사수': 'Spore Shooter',
    '포자 사수의 탄은 옆으로 피하세요.': 'Dodge Spore Shooter bullets sideways.',
    '전투 대기 중': 'Waiting for Combat',
    '작전 실패': 'Mission Failed',
    '위험': 'Danger',
    '준비됨': 'Ready',
    '준비하세요...': 'Get Ready...',
    '오디오 컨텍스트를 생성할 수 없습니다.': 'Cannot create audio context.',
    '다시 도전해 더 높은 웨이브와 점수에 도전하세요.': 'Try again to reach a higher wave and score.',
    '어둠 속에서 살아남아라': 'Survive in the Dark',
    '제로샷 프롬프트 FPS 성능 평가': 'Zero-shot Prompt FPS Benchmark',
    '브라우저 1인칭 미니 FPS': 'Browser 1st Person Mini FPS',
    '던전 FPS': 'Dungeon FPS',
    '던전 서바이버 - 1인칭 FPS 게임': 'Dungeon Survivor - 1st Person FPS Game',
    '던전 서바이버': 'Dungeon Survivor',
    '던전 슈터 3D': 'Dungeon Shooter 3D',
    '던전 프론트라인': 'Dungeon Frontline',
    '네온 던전': 'Neon Dungeon',
    '아니오': 'No',
    '예': 'Yes',
    '점수': 'Score',
    '체력': 'Health',
    '탄약': 'Ammo',
    '웨이브': 'Wave',
    '무기': 'Weapon',
    '이동': 'Move',
    '마우스': 'Mouse',
    '최고': 'Best',
    'title: "던전 서바이버"': 'title: "Dungeon Survivor"',
    'startBtn: "게임 시작"': 'startBtn: "Start Game"',
    'howToPlay: "마우스: 시점 회전\\\\n좌클릭: 사격\\\\nWASD: 이동"': 'howToPlay: "Mouse: Look\\\\nLeft Click: Shoot\\\\nWASD: Move"',
    'healthLabel: "체력"': 'healthLabel: "Health"',
    'scoreLabel: "점수"': 'scoreLabel: "Score"',
    'waveLabel: "웨이브"': 'waveLabel: "Wave"',
    'highLabel: "최고 기록"': 'highLabel: "High Score"',
    'gameOverTitle: "게임 오버"': 'gameOverTitle: "Game Over"',
    'finalScoreLabel: "최종 점수"': 'finalScoreLabel: "Final Score"',
    'restartBtn: "다시 시작"': 'restartBtn: "Restart"',
    '코어 미로: 미니 FPS': 'Core Maze: Mini FPS',
    '3D 미로를 돌파하며 Wave마다 몰려오는 적을 버티세요. 적을 처치해 Score를 쌓고 High Score을 경신하세요.': 'Navigate the 3D maze and survive waves of enemies. Defeat enemies to score and set a new High Score.',
    'WASD Move · Mouse Rotate View · 클릭 사격 · 1/2 Weapon 전환 · Shift 질주': 'WASD Move · Mouse Rotate View · Click Shoot · 1/2 Switch Weapon · Shift Sprint',
    'Start 후 브라우저가 Mouse 포인터 고정을 요청합니다. ESC를 누르면 Pause됩니다.': 'Browser will request pointer lock after starting. Press ESC to pause.',
    '3종': '3 Types',
    '2종': '2 Types',
    '현재 High Score': 'Current High Score',
    '빠르게 접근해 근접 타격합니다.': 'Approaches quickly for melee attacks.',
    '중거리에서 투사체를 Fire합니다.': 'Fires projectiles from mid-range.',
    '느리지만 Health과 공격력이 높습니다.': 'Slow but has high Health and attack power.',
    '의료 키트와 Ammo 상자를 주워 생존 시간을 늘리세요.': 'Pick up medkits and Ammo boxes to increase survival time.',
    '다시 Start': 'Restart',
    '재Start': 'Restart',
    'Wave 보너스 +${n}': 'Wave Bonus +${n}',
    '의 탄은 옆으로 피하세요.': 'bullets: dodge sideways.',
    'Wave 보너스': 'Wave Bonus',
    '의료 키트': 'Medkit',
    '목표: Wave를 버티며 High Score을 갱신하세요.': 'Objective: Survive waves and beat your High Score.',
    '조작:': 'Controls:',
    '- 포인터 잠금 해제 / Pause: ESC': '- Unlock Pointer / Pause: ESC',
    '포인터 잠금이 해제되었습니다.': 'Pointer lock released.',
    '계속하려면 버튼을 누르거나 화면을 클릭하세요.': 'Click screen or button to continue.',
    '재Reloading...': 'Reloading...',
    '화면을 클릭해 조작 Start': 'Click screen to start',
    '클리어!': 'Cleared!',
    '도달 Wave:': 'Wave Reached:',
    'High Score:': 'High Score:',
    '🏆 신기록!': '🏆 New Record!',
    '[ 다시 Start ]': '[ Restart ]',
    '클릭하면 Mouse가 잠깁니다 | ESC: 해제/Pause': 'Click to lock Mouse | ESC: Unlock/Pause',
    '🔋 Ammo 보충!': '🔋 Ammo Refilled!',
    '던전 침입자: 미니 FPS': 'Dungeon Invader: Mini FPS',
    'WASD Move · Mouse 시점 · Left Click 사격 · Wave 생존': 'WASD Move · Mouse View · Left Click Shoot · Survive Waves',
    '조작: WASD Move · Mouse 회전 · Left Click 사격 · Esc 포인터 해제': 'Controls: WASD Move · Mouse Rotate · Left Click Shoot · Esc Unlock Pointer',
    '제작: 브라우저 게임 엔진 · 모든 리소스 코드 내 생성': 'Created: Browser Game Engine · All resources generated in code',
    'Mouse 클릭': 'Mouse Click',
    'WASD로 Move, Mouse로 시점 조절, 클릭으로 공격합니다. Health 아이템을 수집하여 생존 시간을 늘리세요!': 'Move with WASD, rotate view with Mouse, click to attack. Collect Health items to increase survival time!',
    '최종 Score:': 'Final Score:',
    '도달한 Wave:': 'Wave Reached:',
    '새 Wave Start!': 'New Wave Started!',
    'WASD: Move | MOUSE: 조준 & 공격': 'WASD: Move | MOUSE: Aim & Attack',
    'Mouse를 클릭하여 게임을 Start하세요.': 'Click Mouse to Start Game.',
    'LLM 성능 평가용 FPS 엔진 v1.0': 'FPS Engine for LLM Benchmark v1.0',
    'WASD: Move | MOUSE: 시점 & 사격 | ESC: 해제': 'WASD: Move | MOUSE: View & Shoot | ESC: Unlock',
    '- 제로샷 프롬프트로 생성된 게임을 통한 LLM 성능 평가': '- Evaluating LLM Performance via Zero-Shot Prompt-Generated Games',
    'WASD: Move | Mouse: 시점 | 클릭: Fire': 'WASD: Move | Mouse: View | Click: Fire',
    '1인칭 미니 서바이벌': '1st Person Mini Survival',
    'Pointer Lock 자동 활성화': 'Auto-activate Pointer Lock',
    'Wave 클리어 시 다음 Wave 자동 Start': 'Next Wave auto-starts on clear',
    'ESC 키로 Pointer Lock 해제 가능': 'Press ESC to unlock Pointer',
    'WASD — Move\\nMouse - Rotate View\\nLeft Click - Attack\\nPointer Lock 자동 활성화': 'WASD - Move\\nMouse - Rotate View\\nLeft Click - Attack\\nAuto-activate Pointer Lock',
    'WASD: Move | Mouse: 시점 | 클릭: 공격': 'WASD: Move | Mouse: View | Click: Attack',
    'WASD Move | Mouse 시점 | Left Click 공격 | 1:Pistol 2:Shotgun | R 재Start': 'WASD Move | Mouse View | Left Click Attack | 1:Pistol 2:Shotgun | R Restart',
    '클릭 사격': 'Click to Shoot',
    '보호막': 'Shield',
    '신기록!': 'New Record!',
    '점': 'pts',
    '도달 Wave': 'Wave Reached',
    '클릭하면 Mouse가 잠깁니다': 'Click to lock Mouse',
    '해제/Pause': 'Unlock/Pause'
}

import os
d = 'backend/static/games/en/1인칭 미니 FPS'
files = [f for f in os.listdir(d) if f.endswith('.html')]

for f in files:
    filepath = os.path.join(d, f)
    with open(filepath, 'r', encoding='utf-8') as file:
        content = file.read()
    
    for k, v in replacements.items():
        content = content.replace(k, v)
        
    with open(filepath, 'w', encoding='utf-8') as file:
        file.write(content)
        
print('Replacements done.')
