import os
import re

replacements = {
    '8x8 로그라이크 던전': '8x8 Roguelike Dungeon',
    '8x8 2D Roguelike (한 파일)': '8x8 2D Roguelike (Single File)',
    '던전에 진입했습니다.': 'Entered the dungeon.',
    '던전에 입장했다.': 'Entered the dungeon.',
    '던전에 입장': 'Enter Dungeon',
    '던전에서 쓰러졌습니다.': 'Fallen in the dungeon.',
    '던전을 탐험하고 탈출구를 찾아라!': 'Explore the dungeon and find the exit!',
    '도움': 'Help',
    '로그라이크 던전': 'Roguelike Dungeon',
    '무사히 던전을 빠져나왔습니다.': 'Safely escaped the dungeon.',
    '바닥': 'Floor',
    '벽': 'Wall',
    '벽을 뚫고 적 (👾) 을 물리치고 탈출구 (🚪) 를 찾으세요.': 'Break walls, defeat enemies (👾), and find the exit (🚪).',
    '빈 바닥': 'Empty Floor',
    '상태': 'Status',
    '설명': 'Description',
    '시야 바깥은 보이지 않으며, 적과 마주치면 전투가 시작됩니다.': 'Outside vision is hidden, combat starts upon encountering enemies.',
    '아이템: 닿으면 회복': 'Item: Touch to heal',
    '어둠 속 던전에 갇혔다.': 'Trapped in a dark dungeon.',
    '이동: 방향키 또는 WASD': 'Move: Arrow keys or WASD',
    '이동할 때마다 적도 한 번 행동합니다.': 'Enemies act once per every move.',
    '입장하기': 'Enter',
    '재시작': 'Restart',
    '적': 'Enemy',
    '적 HP': 'Enemy HP',
    '적 체력': 'Enemy Health',
    '적과 부딪히면 서로 체력이 감소합니다.': 'Colliding with enemies reduces health for both.',
    '적과 접촉하면 전투 발생': 'Combat occurs on contact with an enemy',
    '적과의 전투에서 쓰러졌습니다.': 'Fallen in combat with an enemy.',
    '적을 처치했습니다.': 'Enemy defeated.',
    '적의 공격에 쓰러졌습니다.': 'Fallen by enemy attack.',
    '적이 쓰러졌습니다.': 'Enemy has fallen.',
    '적이 접근해 전투가 발생했다.': 'Enemy approached and combat started.',
    '점수': 'Score',
    '점수:': 'Score:',
    '제작: 한 파일 HTML/CSS/JS · Fog of War 포함': 'Created: Single HTML/CSS/JS file · Includes Fog of War',
    '조작': 'Controls',
    '처치한 적:': 'Defeated Enemies:',
    '체력': 'Health',
    '체력:': 'Health:',
    '체력이 0이 되었습니다.': 'Health reached 0.',
    '최종 점수:': 'Final Score:',
    '최종 점수: 0': 'Final Score: 0',
    '최종 처치:': 'Final Kills:',
    '층:': 'Floor:',
    '탈출구': 'Exit',
    '탈출구(🚪)에 도달하면 승리합니다': 'Reach the exit (🚪) to win',
    '탈출구를 찾아 던전에서 살아 나왔습니다.': 'Found the exit and survived the dungeon.',
    '탈출구를 찾아 살아남아라.': 'Find the exit and survive.',
    '탈출구를 찾아 이동하라.': 'Move to find the exit.',
    '탈출구에 도달했습니다!': 'Reached the exit!',
    '탈출구에 도달했습니다. 승리!': 'Reached the exit. Victory!',
    '탈출에 성공했습니다!': 'Escaped successfully!',
    '턴 수': 'Turns',
    '턴 수:': 'Turns:',
    '턴:': 'Turn:',
    '턴제 이동 • 주변만 보임': 'Turn-based Movement • Limited Vision',
    '플레이 방법': 'How to Play',
    '플레이어': 'Player',
    '플레이어 HP': 'Player HP',
    '플레이어(P)로 이동해 적(E)을 상대하고, 아이템(I)으로 회복하며, 탈출구(O)로 빠져나오세요.': 'Move Player(P) to fight Enemy(E), heal with Item(I), and escape through Exit(O).',
    '플레이어는 P, 적은 E, 아이템은 I, 탈출구는 O': 'Player is P, Enemy is E, Item is I, Exit is O',
    '화살표': 'Arrow',
    '회복 아이템': 'Recovery Item',
    '회복 아이템(❤️)을 먹으면 체력이 회복됩니다': 'Eat recovery item (❤️) to restore health',
    '회복 아이템을 먹고 살아남아 탈출구까지 도달하세요.': 'Eat recovery items, survive, and reach the exit.',
    '던전 크롤러': 'Dungeon Crawler',
    '적과 부딪히면 전투! 회복!': 'Combat on collision! Heal!',
    '적 — 접촉 시 전투': 'Enemy - Combat on contact',
    '회복 아이템 (+3 HP)': 'Recovery Item (+3 HP)',
    '탈출구 — 도달하면 승리': 'Exit - Reach to win',
    '플레이어 (HP 10)': 'Player (HP 10)',
    '벽 — 통과 불가': 'Wall - Cannot pass',
    '벽이다.': 'It\'s a wall.',
    '게임 시작': 'Start Game',
    '다시 시작': 'Restart',
    '새 게임': 'New Game',
    '게임 오버': 'Game Over',
    '게임 오버.': 'Game Over.',
    '게임 종료': 'Game Over',
    '승리!': 'Victory!',
    '패배': 'Defeat',
    '패배...': 'Defeat...',
    '사망': 'Died',
    '탈출 성공!': 'Escape Successful!',
    '던전 탈출': 'Dungeon Escape',
    '던전 로그라이크': 'Dungeon Roguelike',
    '던전 탐험을 시작하세요...': 'Begin your dungeon exploration...',
    '던전에 들어왔습니다.': 'Entered the dungeon.',
    '8x8 랜덤 던전 · 턴제 · Fog of War': '8x8 Random Dungeon · Turn-based · Fog of War',
    '방향키 또는 WASD로 플레이어(🧙)를 이동시킵니다': 'Move player (🧙) with Arrow keys or WASD',
    '안개(Fog of War) 때문에 주변만 볼 수 있습니다': 'You can only see the surroundings due to Fog of War',
    '적(👹)과 만나면 서로 체력을 잃습니다': 'Meet enemies (👹) and lose health',
    '탈출구(🚪)에 도달하면 승리합니다': 'Reach the exit (🚪) to win',
    '던전 로그라이크': 'Dungeon Roguelike',
    '던전에 입장했습니다. 🚪를 찾으세요!': 'Entered the dungeon. Find 🚪!',
    '이동할 때마다 적도 한 번 행동합니다.': 'Enemies move once per your move.',
    '다시 플레이할 수 있습니다.': 'You can play again.',
    '탈출구에 도달했습니다. 승리!': 'Reached the exit. Victory!',
    '당신은 던전에서 쓰러졌습니다.': 'You have fallen in the dungeon.',
    '당신은 던전의 이슬로 사라졌습니다.': 'You vanished into the dungeon dew.',
    '모든 던전탈출 성공했습니다!': 'Escaped all dungeons successfully!',
    '바위 벽에 막혔습니다.': 'Blocked by a rock wall.',
    '방식입니다.': 'style.',
    '방향키 / WASD 로 이동': 'Move with Arrow keys / WASD',
    '방향키 또는': 'Arrow keys or',
    '방향키 또는 WASD': 'Arrow keys or WASD',
    '방향키 또는 WASD 로 이동하세요.': 'Move with Arrow keys or WASD.',
    '방향키 또는 WASD로 이동하세요.': 'Move with Arrow keys or WASD.',
    '벽 너머로는 갈 수 없다.': 'Cannot go beyond the wall.',
    '벽 바깥으로는 나갈 수 없습니다.': 'Cannot go outside the wall.',
    '벽 🪨\u2003랜덤 생성 • 탈출 가능 보장': 'Wall 🪨 Random generation • Escape guaranteed',
    '벽이 가로막고 있습니다.': 'A wall is blocking the way.',
    '벽이 길을 막고 있다.': 'A wall blocks the path.',
    '시야는 플레이어 주변만 보이는': 'Vision is limited to the player\'s surroundings',
    '적을 피하거나 쓰러뜨리고': 'Avoid or defeat enemies',
    '주변 2칸만 보입니다. 턴제 진행': 'Only 2 cells visible around. Turn-based',
    '주변만 보입니다. 조심해서 이동하세요.': 'Only surroundings visible. Move carefully.',
    '던전에 발을 들였다. 탈출구를 찾아라! 🚪': 'Stepped into the dungeon. Find the exit! 🚪',
    '이동: WASD 또는 화살표\\n적과 접촉하면 전투 발생(서로 체력 감소)\\n아이템(💊)은 닿으면 +4 회복\\n탈출구(🚪)에 도 달하면 승리\\n재시작 버튼으로 완전 초기화': 'Move: WASD or Arrows\\nCombat on enemy contact (both lose HP)\\nItem (💊) heals +4 HP\\nReach exit (🚪) to win\\nRestart button to reset completely',
    '이동: WASD 또는 화살표\\n적과 접촉하면 전투 발생(서로 체력 감소)\\n아이템(💊)은 닿으면 +4 회복\\n탈출구(🚪)에 도달하면 승리\\n재시작 버튼으로 완전 초기화': 'Move: WASD or Arrows\\nCombat on enemy contact (both lose HP)\\nItem (💊) heals +4 HP\\nReach exit (🚪) to win\\nRestart button to reset completely',
    '↑↓←→ 또는 WASD\u2003•\u2003주변만 보이는 Fog of War': '↑↓←→ or WASD\u2003•\u2003Fog of War',
    '↩ 재시작': '↩ Restart',
    '▶ 게임 시작': '▶ Start Game',
    '⚔️ 8x8 던전 ⚔️': '⚔️ 8x8 Dungeon ⚔️',
    '⚔️ 8x8 로그라이크 던전': '⚔️ 8x8 Roguelike Dungeon',
    '⚔️ 던전 탈출 ⚔️': '⚔️ Dungeon Escape ⚔️',
    '게임 보드': 'Game Board',
    '공격력': 'Attack Power',
    '기호': 'Symbol',
    '다시하기': 'Play Again',
    '던전': 'Dungeon',
    '또는': 'or',
    '로 한 칸씩 이동합니다.': 'to move one cell.',
    '로그': 'Log',
    '로그라이크': 'Roguelike',
    '사망': 'Dead',
    '적을 처치했습니다!': 'Defeated enemy!',
    '적을 처치했다!': 'Defeated enemy!',
    '체력이 다 떨어졌다.': 'Health depleted.',
    '던전을 탈출했다!': 'Escaped the dungeon!',
    '보너스': 'Bonus',
    '마리': ' monsters',
    '처치:': 'Kills:',
    '턴:': 'Turn:',
    '점': 'pts',
    '💀 적을 처치했다!': '💀 Enemy defeated!',
    '🚶 이동': '🚶 Move',
    '💊 회복 아이템!': '💊 Recovery Item!',
    '현재:': 'Current:',
    '회복!': 'Healed!',
    '회복 아이템 (+3 HP)': 'Recovery Item (+3 HP)',
    '탈출구 — 도달하면 승리': 'Exit - Reach to win',
    '플레이어 (HP 10)': 'Player (HP 10)',
    '벽 — 통과 불가': 'Wall - Cannot pass',
    '적 — 접촉 시 전투': 'Enemy - Combat on contact',
    '적과 부딪히면 전투! 회복!': 'Combat on collision! Heal!',
    '던전 크롤러': 'Dungeon Crawler',
    '🎉 승리': '🎉 Victory',
    '💀 게임 오버': '💀 Game Over',
    '💀 사망': '💀 Dead',
    '💀 패배': '💀 Defeat',
    '💀 패배...': '💀 Defeat...',
    '💊 회복 아이템 (+3 HP)': '💊 Recovery Item (+3 HP)',
    '🕯️ 던전에 입장': '🕯️ Entered the dungeon',
    '🗡️ 8x8 로그라이크 던전': '🗡️ 8x8 Roguelike Dungeon',
    '🗺️ 8x8 랜덤 던전 · 턴제 · Fog of War': '🗺️ 8x8 Random Dungeon · Turn-based · Fog of War',
    '🚪 탈출구 — 도달하면 승리': '🚪 Exit — Reach to win',
    '🧙 플레이어 (HP 10)': '🧙 Player (HP 10)',
    '🧱 벽 — 통과 불가': '🧱 Wall — Cannot pass',
    '🧱 벽이다.': '🧱 It\'s a wall.',
    '적(👹)과 만나면 서로 체력을 잃습니다': 'Meet enemies (👹) and lose health',
    '탈출구(🚪)에 도달하면 승리합니다': 'Reach the exit (🚪) to win',
    '방향키 또는 WASD로 플레이어(🧙)를 이동시킵니다': 'Move player (🧙) with Arrow keys or WASD',
    '안개(Fog of War) 때문에 주변만 볼 수 있습니다': 'You can only see surroundings due to Fog of War',
    '제작: 한 파일 HTML/CSS/JS · Fog of War 포함': 'Created: Single HTML/CSS/JS file · Includes Fog of War',
    '최종 처치:': 'Final Kills:',
    '최종 점수:': 'Final Score:',
    '체력이 0이 되었습니다.': 'Health reached 0.',
    '적을 피하거나 쓰러뜨리고': 'Avoid or defeat enemies',
    '탈출구를 찾아 살아남아라.': 'Find the exit and survive.',
    '시야는 플레이어 주변만 보이는': 'Vision is limited to the player surroundings',
    '방식입니다.': 'style.',
    '방향키 또는 WASD 로 이동하세요.': 'Move with Arrow keys or WASD.',
    '방향키 또는 WASD로 이동하세요.': 'Move with Arrow keys or WASD.',
    '벽 너머로는 갈 수 없다.': 'Cannot go beyond the wall.',
    '벽 바깥으로는 나갈 수 없습니다.': 'Cannot go outside the wall.',
    '벽 🪨\u2003랜덤 생성 • 탈출 가능 보장': 'Wall 🪨 Random generation • Escape guaranteed',
    '벽이 가로막고 있습니다.': 'A wall is blocking the way.',
    '벽이 길을 막고 있다.': 'A wall blocks the path.',
    '시야 바깥은 보이지 않으며, 적과 마주치면 전투가 시작됩니다.': 'Outside vision is hidden, combat starts upon encountering enemies.',
    '어둠 속 던전에 갇혔다.': 'Trapped in a dark dungeon.',
    '이동: 방향키 또는 WASD': 'Move: Arrow keys or WASD',
    '이동할 때마다 적도 한 번 행동합니다.': 'Enemies act once per every move.',
    '입장하기': 'Enter',
    '적과 부딪히면 서로 체력이 감소합니다.': 'Colliding with enemies reduces health for both.',
    '적과 접촉하면 전투 발생': 'Combat occurs on contact with an enemy',
    '적과의 전투에서 쓰러졌습니다.': 'Fallen in combat with an enemy.',
    '적의 공격에 쓰러졌습니다.': 'Fallen by enemy attack.',
    '적이 쓰러졌습니다.': 'Enemy has fallen.',
    '적이 접근해 전투가 발생했다.': 'Enemy approached and combat started.',
    '주변 2칸만 보입니다. 턴제 진행': 'Only 2 cells visible around. Turn-based',
    '주변만 보입니다. 조심해서 이동하세요.': 'Only surroundings visible. Move carefully.',
    '던전에 발을 들였다. 탈출구를 찾아라! 🚪': 'Stepped into the dungeon. Find the exit! 🚪',
    '↑↓←→ 또는 WASD\u2003•\u2003주변만 보이는 Fog of War': '↑↓←→ or WASD\u2003•\u2003Fog of War',
    '↩ 재시작': '↩ Restart',
    '▶ 게임 시작': '▶ Start Game',
    '⚔️ 8x8 던전 ⚔️': '⚔️ 8x8 Dungeon ⚔️',
    '게임 보드': 'Game Board',
    '공격력': 'Attack Power',
    '기호': 'Symbol',
    '다시하기': 'Play Again',
    '던전': 'Dungeon',
    '또는': 'or',
    '로 한 칸씩 이동합니다.': 'to move one cell.',
    '로그': 'Log',
    '로그라이크': 'Roguelike',
    '적을 처치했다!': 'Defeated enemy!',
    '체력이 다 떨어졌다.': 'Health depleted.',
    '던전을 탈출했다!': 'Escaped the dungeon!',
    '보너스': 'Bonus',
    '마리': ' monsters',
    '처치:': 'Kills:',
    '턴:': 'Turn:',
    '점': 'pts',
    '💀 적을 처치했다!': '💀 Enemy defeated!',
    '🚶 이동': '🚶 Move',
    '💊 회복 아이템!': '💊 Recovery Item!',
    '현재:': 'Current:',
    '회복!': 'Healed!',
    '탈출에 성공했습니다!': 'Escaped successfully!',
    '탈출구를 찾아 던전에서 살아 나왔습니다.': 'Found the exit and survived the dungeon.',
    '탈출구에 도달했습니다!': 'Reached the exit!',
    '탈출구에 도달했습니다. 승리!': 'Reached the exit. Victory!',
    '당신은 던전에서 쓰러졌습니다.': 'You have fallen in the dungeon.',
    '당신은 던전의 이슬로 사라졌습니다.': 'You vanished into the dungeon dew.',
    '모든 던전탈출 성공했습니다!': 'Escaped all dungeons successfully!',
    '바위 벽에 막혔습니다.': 'Blocked by a rock wall.',
    '방향키 / WASD 로 이동': 'Move with Arrow keys / WASD',
    '방향키 또는': 'Arrow keys or',
    '방향키 또는 WASD': 'Arrow keys or WASD',
    '시야는 플레이어 주변만 보이는': 'Vision is limited to the player surroundings',
    '적을 피하거나 쓰러뜨리고': 'Avoid or defeat enemies',
    '탈출구를 찾아 살아남아라.': 'Find the exit and survive.',
    '탈출구를 찾아 이동하라.': 'Move to find the exit.',
    '탈출구': 'Exit',
    '턴 수': 'Turns',
    '턴 수:': 'Turns:',
    '턴제 이동 • 주변만 보임': 'Turn-based Movement • Limited Vision',
    '플레이 방법': 'How to Play',
    '플레이어': 'Player',
    '플레이어 HP': 'Player HP',
    '플레이어(P)로 이동해 적(E)을 상대하고, 아이템(I)으로 회복하며, 탈출구(O)로 빠져나오세요.': 'Move Player(P) to fight Enemy(E), heal with Item(I), and escape through Exit(O).',
    '플레이어는 P, 적은 E, 아이템은 I, 탈출구는 O': 'Player is P, Enemy is E, Item is I, Exit is O',
    '화살표': 'Arrow',
    '회복 아이템': 'Recovery Item',
    '회복 아이템(❤️)을 먹으면 체력이 회복됩니다': 'Eat recovery item (❤️) to restore health',
    '회복 아이템을 먹고 살아남아 탈출구까지 도달하세요.': 'Eat recovery items, survive, and reach the exit.',
    '적을 처치했습니다!': 'Defeated enemy!',
    '적을 처치했습니다.': 'Defeated enemy.',
    '무사히 던전을 빠져나왔습니다.': 'Safely escaped the dungeon.',
    '던전을 탐험하고 탈출구를 찾아라!': 'Explore the dungeon and find the exit!',
    '던전에서 쓰러졌습니다.': 'Fallen in the dungeon.',
    '던전에 들어왔습니다.': 'Entered the dungeon.',
    '던전 탐험을 시작하세요...': 'Begin your dungeon exploration...',
    '던전 탈출': 'Dungeon Escape',
    '사망': 'Dead',
    '패배...': 'Defeat...',
    '패배': 'Defeat',
    '승리!': 'Victory!',
    '게임 종료': 'Game Over',
    '게임 오버.': 'Game Over.',
    '게임 오버': 'Game Over',
    '새 게임': 'New Game',
    '다시 시작': 'Restart',
    '게임 시작': 'Start Game',
}

import re
# Sort keys by length descending to replace longer phrases first
sorted_keys = sorted(replacements.keys(), key=len, reverse=True)

d = 'backend/static/games/en/던전 탐색'
files = [f for f in os.listdir(d) if f.endswith('.html')]

for f in files:
    filepath = os.path.join(d, f)
    with open(filepath, 'r', encoding='utf-8') as file:
        content = file.read()
    
    for k in sorted_keys:
        v = replacements[k]
        content = content.replace(k, v)
        
    with open(filepath, 'w', encoding='utf-8') as file:
        file.write(content)
        
print('Replacements for Dungeon Explorer done.')
